services:
  mysql:
    image: inseratdb
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=inserat
      - MYSQL_PASSWORD=pzsjh68sDfV5tmDY3GVs
      - MYSQL_USER=admin
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./db:/var/lib/mysql
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  flask:
    build: .
    container_name: flask
    restart: always
    environment:
        - DATABASE_URL=mysql+pymysql://admin:mysqlserver@dbserver/inserat
    volumes:
      - ./app:/app:ro
    depends_on:
      - mysql
    links:
      - mysql:dbserver