"""last and firstname

Revision ID: 28849657b08d
Revises: 0f09cd1d1ed1
Create Date: 2023-05-21 03:44:15.946573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28849657b08d'
down_revision = '0f09cd1d1ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
