"""added timestamp for Advertisement

Revision ID: 460d1a1d2681
Revises: a9b4b47b93f7
Create Date: 2023-05-31 15:01:47.402785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460d1a1d2681'
down_revision = 'a9b4b47b93f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisement', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
